name: Veracode Scan

on: 
  pull_request:
    branches-ignore:
      - master

  push:
    branches-ignore:
      - master

env:
  JAVA_WRAPPER_VERSION: "20.3.6.1" # Update the version when new version is released.
  APP_NAME: "Veracode Jenkins Plugin"
  SANDBOX_NAME: "GitHub Open Source Sandbox"

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Download Java Wrapper
      run: |
        echo 'Java Wrapper Version - '"${{ env.JAVA_WRAPPER_VERSION }}"
        curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/"${{ env.JAVA_WRAPPER_VERSION }}"/vosp-api-wrappers-java-"${{ env.JAVA_WRAPPER_VERSION }}".jar -o VeracodeJavaAPI.jar
    
    - name: Scan with Java Wrapper
      run: java -jar VeracodeJavaAPI.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -action UploadAndScan -appname "${{ env.APP_NAME }}" -createprofile true -sandboxname "${{ env.SANDBOX_NAME }}" -createsandbox true -filepath target/veracode-scan.jar -version "$(date +'%Y-%m-%d-%H:%M:%S')" 


  sca-scan:

    runs-on: ubuntu-latest
    
    continue-on-error: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: SCA Scan
      run: mvn compile com.srcclr:srcclr-maven-plugin:scan -DapiToken=${{ secrets.SRCCLR_API_TOKEN }}